set_property SRC_FILE_INFO {cfile:/opt/Xilinx/Vivado/2018.3/bin/reloj/reloj.srcs/constrs_1/new/pines_basys3.xdc rfile:../../../reloj.srcs/constrs_1/new/pines_basys3.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W5 [get_ports clk]
set_property src_info {type:XDC file:1 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U16 [get_ports led]
